const express = require('express')
const verifyToken = require('../middleware/auth')
const { getRandomPost } = require('../controllers/postController/getRandomPost')
const { getProfileShowData } = require('../controllers/profileController/getProfileShow')
const { getCommentOrLike } = require('../controllers/postController/getCommentOrLike')
const { getFollowData } = require('../controllers/profileController/getFollowerData')
const { getUser } = require('../controllers/profileController/getUser')
const { getUserPosts } = require('../controllers/postController/getUserPosts')
const getRouter = express.Router()
getRouter.get('/random-post', verifyToken, getRandomPost)
getRouter.get('/profile-show/:username', getProfileShowData)
getRouter.get('/fetch-comment-or-like/:postId', verifyToken, getCommentOrLike)
getRouter.get('/follow-data/:type', verifyToken, getFollowData)
getRouter.get('/user',verifyToken,getUser)
getRouter.get('/user/post/:userId',verifyToken,getUserPosts)
module.exports = { getRouter }