const express = require('express')
const verifyToken = require('../middleware/auth')
const { updateLikes } = require('../controllers/postController/likeController')
const { updateComment } = require('../controllers/postController/commentController')
const { updateFollower } = require('../controllers/profileController/updateFollower')
const updateRouter = express.Router()
updateRouter.put('/likes/:postId',verifyToken,updateLikes)
updateRouter.post('/:postId/comment',verifyToken,updateComment)
updateRouter.put('/follower/:follower_id',verifyToken,updateFollower)
module.exports={updateRouter}